package os.kei.baselineprofile

/**
 * Every test tag the profile generator and the frame benchmarks wait for, spelled once.
 *
 * This module cannot depend on the app's source set, so the tags are re-spelled here as strings.
 * `BaselineProfileTestTagContractTest` checks each one against the app, which is where a drift between
 * the two spellings would otherwise surface: on a device, minutes into a capture, as a timeout. The two
 * files used to carry their own copies, and a tag renamed in one would have passed in the other.
 */

internal const val MAIN_BOTTOM_TAB_HOME = "main_bottom_tab_home"
internal const val MAIN_BOTTOM_TAB_OS = "main_bottom_tab_os"
internal const val MAIN_BOTTOM_TAB_MCP = "main_bottom_tab_mcp"
internal const val MAIN_BOTTOM_TAB_GITHUB = "main_bottom_tab_github"
internal const val MAIN_BOTTOM_TAB_BA = "main_bottom_tab_ba"
internal const val MAIN_SIDEBAR_TOGGLE = "main_sidebar_toggle"
internal const val MAIN_SIDEBAR_ROW_HOME = "main_sidebar_row_home"
internal const val MAIN_SIDEBAR_ROW_MCP = "main_sidebar_row_mcp"
internal const val MAIN_SIDEBAR_ROW_GITHUB = "main_sidebar_row_github"
internal const val MAIN_SIDEBAR_ROW_BA = "main_sidebar_row_ba"
internal const val MAIN_PAGER_SETTLED_HOME = "main_pager_settled_home"
internal const val MAIN_PAGER_SETTLED_OS = "main_pager_settled_os"
internal const val MAIN_PAGER_SETTLED_MCP = "main_pager_settled_mcp"
internal const val MAIN_PAGER_SETTLED_GITHUB = "main_pager_settled_github"
internal const val MAIN_PAGER_SETTLED_BA = "main_pager_settled_ba"
internal const val HOME_PAGE_ROOT = "home_page_root"
internal const val HOME_SETTINGS_BUTTON = "home_settings_button"
internal const val HOME_ABOUT_BUTTON = "home_about_button"
internal const val HOME_WEBDAV_CARD = "home_webdav_card"
internal const val SETTINGS_PAGE_ROOT = "settings_page_root"
internal const val SETTINGS_TAB_INTERFACE = "settings_tab_2"
internal const val SETTINGS_THEME_MODE_SELECTOR = "settings_theme_mode_selector"
internal const val SNAPSHOT_MENU_PANEL = "snapshot_menu_panel"
internal const val ABOUT_PAGE_ROOT = "about_page_root"
internal const val WEBDAV_SYNC_PAGE_ROOT = "webdav_sync_page_root"
internal const val OS_PAGE_ROOT = "os_page_root"
internal const val OS_SHELL_RUNNER_BUTTON = "os_shell_runner_button"
internal const val OS_SHELL_RUNNER_PAGE_ROOT = "os_shell_runner_page_root"
internal const val MCP_PAGE_ROOT = "mcp_page_root"
internal const val MCP_SKILL_BUTTON = "mcp_skill_button"
internal const val MCP_SKILL_PAGE_ROOT = "mcp_skill_page_root"
internal const val GITHUB_PAGE_ROOT = "github_page_root"
internal const val GITHUB_TRACKED_ITEM_CARD_FIRST = "github_tracked_item_card_first"
internal const val GITHUB_TRACKED_ITEM_MORE_BUTTON = "github_tracked_item_more_button"
internal const val GITHUB_ACTIONS_MENU_ITEM = "github_actions_menu_item"
internal const val GITHUB_ADD_TRACKED_BUTTON = "github_add_tracked_button"
internal const val GITHUB_STRATEGY_SHEET_BUTTON = "github_strategy_sheet_button"
internal const val GITHUB_IMPORT_MENU_BUTTON = "github_import_menu_button"
internal const val GITHUB_IMPORT_TRACKS = "github_import_tracks"
internal const val GITHUB_ACTIONS_HISTORY_BUTTON = "github_actions_history_button"
internal const val GITHUB_ACTIONS_HISTORY_PAGE_ROOT = "github_actions_history_page_root"
internal const val GITHUB_HISTORY_TAB_ACTIONS = "github_history_tab_1"
internal const val GITHUB_HISTORY_TAB_TRACKING = "github_history_tab_2"
internal const val BA_PAGE_ROOT = "ba_page_root"
internal const val BA_COOLDOWN_CARD_FIRST = "ba_cooldown_card_first"
internal const val BA_COOLDOWN_ADJUST_BUTTON = "ba_cooldown_adjust_button"
internal const val BA_DOCK_OPEN_CALENDAR_POOL = "ba_dock_open_calendar_pool"
internal const val BA_CALENDAR_POOL_PAGE_ROOT = "ba_calendar_pool_page_root"
internal const val BA_CALENDAR_POOL_TAB_POOL = "ba_calendar_pool_tab_1"
internal const val BA_DOCK_OPEN_GUIDE_CATALOG = "ba_dock_open_guide_catalog"
internal const val BA_DOCK_DAILY_DONE = "ba_dock_daily_done"
internal const val BA_GUIDE_CATALOG_PAGE_ROOT = "ba_guide_catalog_page_root"
internal const val BA_GUIDE_CATALOG_ENTRY_FIRST = "ba_guide_catalog_entry_first"
internal const val BA_STUDENT_GUIDE_PAGE_ROOT = "ba_student_guide_page_root"
internal const val BA_STUDENT_GUIDE_TAB_SKILLS = "ba_student_guide_tab_skills"
internal const val BA_STUDENT_GUIDE_SIDEBAR_TOGGLE = "ba_student_guide_sidebar_toggle"
internal const val BA_STUDENT_GUIDE_SIDEBAR_ROW_SKILLS = "ba_student_guide_tab_skills_sidebar_row"
internal const val BA_STUDENT_GUIDE_TAB_PROFILE = "ba_student_guide_tab_profile"
internal const val BA_STUDENT_GUIDE_TAB_VOICE = "ba_student_guide_tab_voice"
internal const val BA_GUIDE_CATALOG_DOCK_MEMORY_LOBBY = "ba_guide_catalog_dock_memory_lobby"
internal const val BA_GUIDE_CATALOG_DOCK_STUDENT_BGM = "ba_guide_catalog_dock_student_bgm"
internal const val BA_GUIDE_CATALOG_DOCK_FAVORITE_BGM = "ba_guide_catalog_dock_favorite_bgm"
internal const val BA_GUIDE_CATALOG_STUDENT_BGM_FIRST = "ba_guide_catalog_student_bgm_first"
internal const val BA_GUIDE_CATALOG_BGM_PLAYING = "ba_guide_catalog_bgm_playing"
internal const val COMPACT_BOTTOM_BAR_DOCK = "compact_bottom_bar_dock"
internal const val LIQUID_SHEET_PANEL = "liquid_sheet_panel"
internal const val LIQUID_SHEET_DRAG_REGION = "liquid_sheet_drag_region"

internal const val GUIDE_MODEL3D_READY = "guide_model3d_ready"
internal const val GUIDE_LOBBY_READY = "guide_lobby_ready"
